export default [
    {title: "EXO", length: "3:26", artistID: 1},
    {title: "STAY AWAY", length: "5:24", artistID: 2},
    {title: "Weltschmerz", length: "6:24",artistID: 4},
    {title: "Imposter", length: "4:48",artistID: 3},
    {title: "PLASTIC MINCER", length: "3:44",artistID: 1},
    {title: "LUCID", length: "4:42",artistID: 1},
    {title: "Behoorlijke Beuker 2", length: "3:05",artistID: 1},
    {title: "She Left Crying ", length: "4:37",artistID: 2},
    {title: "See You In Hell", length: "5:39",artistID: 2},
    {title: "RED BUNKER", length: "5:07",artistID: 2},
    {title: "Bad Vibes", length: "4:12",artistID: 2},
    {title: "Crying in your sleep", length: "5:55",artistID: 3},
    {title: "Don't Leave", length: "5:44",artistID: 3},
    {title: "Scare Them", length: "5:01",artistID: 3},
    {title: "Die Welt Brennt", length: "5:10",artistID: 4},
    {title: "Deine Angst", length: "5:21",artistID: 4},
    {title: "Mein Wille", length: "4:25",artistID: 4},
    {title: "Engelsblut", length: "5:59",artistID: 4},
]